import java.io.*;
import java.nio.charset.StandardCharsets;

// Various util functions and constants
class Util {

    // Help text shown on invalid args
    private static final String HELP = """
            CTP - Code To PlantUML

            Usage: ctp [lang] [path] [output]

            Languages: java | cpp
            Path: a path to a folder to scan (must be inside the current directory)
            Output: the name of output diagram file (generally ending in .puml)

            Examples:
            ctp cpp src diagram.puml
            ctp cpp . classdiagram.plantuml
            ctp java app/src/main/org/example/stack stack.puml
            ctp java src/ project.puml

            Repository: https://github.com/samuelroland/ctp
            """;

    // Delimiters for static section
    private static final String STATIC_START = "STATIC";
    private static final String STATIC_END = "ENDSTATIC";
    private static final String STATIC_REMOVE_KW = "REMOVE";
    private static final String STATIC_REPLACE_KW = "REPLACE"; // TODO: implement this
    private static final String START_MARKER_PUML = "@startuml\n";

    // Default content of the static section in output file
    private static final String STATIC_DEFAULT_CONTENT = "' " + STATIC_START + """
            ' Auto generated by CTP - https://github.com/samuelroland/ctp
            '
            ' """ + STATIC_REMOVE_KW + """

            ' """ + STATIC_END + "\n";

    private Util() {
    }

    public static void printHelp() {
        System.out.println(HELP);
    }

    public static String getDefaultStaticText() {
        return STATIC_DEFAULT_CONTENT;
    }

    //
    public static String readEntireStream(InputStream stream) {
        String text = "";
        try (var reader = new BufferedReader(
                new InputStreamReader(stream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                text += line + "\n";
            }
        } catch (Exception e) {
            System.out.println("Error reading stream: " + e);
        }

        return text;
    }

    public static String readEntireFile(String path) {
        try (var stream = new FileInputStream(path)) {
            return Util.readEntireStream(stream);
        } catch (Exception e) {
            CLI.fail("Failed to read file " + path);
            return null;
        }
    }

    // Push the static section (just add id after @startuml) in given PUML schema
    public static String pushStaticSection(String schema, String staticSection) {
        if (schema.indexOf(START_MARKER_PUML) == -1)
            CLI.fail("Error: temp diagram file has no @startuml directive... Failed to insert static section.");

        return START_MARKER_PUML + "\n" + staticSection + "\n" + schema.substring(START_MARKER_PUML.length());
    }

    // Look in given schema if already contains a static section to know if we need
    // to insert a default one
    public static boolean doesContainStaticSection(String schema) {
        int startPos = schema.indexOf(STATIC_START);
        int endPos = schema.indexOf(STATIC_END, startPos);
        return startPos != -1 && endPos != -1;
    }
}